brew "asdf"
brew "bat"
brew "bottom"
brew "coreutils"
brew "curl"
brew "fish"
brew "gdu"
brew "git"
brew "lazygit"
brew "lsd"
brew "neovim"
brew "ripgrep"
brew "starship"

cask "alacritty"
cask "font-jetbrains-mono-nerd-font"
cask "google-japanese-ime"
